#pragma once
#include <module.h>

// The implementation is generated by CMake at the top-level CMakeLists.txt
// from `core/src/static_modules.cpp.in`, driven by the
// SDRPP_STATIC_MODULE_TARGETS list that sdrpp_module.cmake populates.
void registerStaticModules();

// Each module's main.cpp gets SDRPP_MODULE_TOKEN=<name>_ at compile time,
// which renames the five fixed entry-point symbols (see module.h). The
// generated registry redeclares those renamed symbols with C linkage and
// passes them to ModuleManager::registerStatic.
#define SDRPP_DECLARE_STATIC_MOD(tok)                                        \
    extern "C" {                                                             \
        extern const ModuleManager::ModuleInfo_t tok##_INFO_;                \
        void tok##_INIT_();                                                  \
        ModuleManager::Instance* tok##_CREATE_INSTANCE_(std::string);        \
        void tok##_DELETE_INSTANCE_(ModuleManager::Instance*);               \
        void tok##_END_();                                                   \
    }

#define SDRPP_REGISTER_STATIC_MOD(tok)                                       \
    core::moduleManager.registerStatic(                                      \
        const_cast<ModuleManager::ModuleInfo_t*>(&tok##_INFO_),              \
        tok##_INIT_,                                                         \
        tok##_CREATE_INSTANCE_,                                              \
        tok##_DELETE_INSTANCE_,                                              \
        tok##_END_                                                           \
    );
