// VOLK shim for iOS — exports just the subset of the VOLK API that SDR++
// actually calls. Implementations live in ios/volk_shim/volk_shim.cpp and
// use Apple's Accelerate framework (vDSP) where it pays, scalar code (which
// the arm64 compiler vectorizes well at -O3) elsewhere.
//
// Real VOLK ships a lot more API surface and a runtime kernel-dispatch
// generator; we don't need any of that on a single-arch iOS target.
//
// Generated by `grep -rh -oE "volk_[a-zA-Z0-9_]+"` against the SDR++ tree —
// if you add a SDR++ dep that calls a VOLK function not listed here, the
// link will fail loudly with an undefined-symbol error pointing at it.

#pragma once
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
#include <complex>
typedef std::complex<float> lv_32fc_t;
// Real VOLK ships lv_cmake() as a constructor macro; SDR++'s frequency_xlator
// uses it to build phasors from sin/cos pairs.
#define lv_cmake(re, im) lv_32fc_t((float)(re), (float)(im))
extern "C" {
#else
#include <complex.h>
typedef _Complex float lv_32fc_t;
#define lv_cmake(re, im) ((float)(re) + (float)(im) * I)
#endif

// ---- Allocator ---------------------------------------------------------
void*  volk_malloc(size_t size, size_t alignment);
void   volk_free(void* ptr);
size_t volk_get_alignment(void);

// ---- Real-vector arithmetic --------------------------------------------
void volk_32f_x2_add_32f      (float* c, const float* a, const float* b, unsigned int n);
void volk_32f_x2_subtract_32f (float* c, const float* a, const float* b, unsigned int n);
void volk_32f_x2_multiply_32f (float* c, const float* a, const float* b, unsigned int n);
void volk_32f_s32f_multiply_32f(float* c, const float* a, float k,        unsigned int n);
void volk_32f_x2_dot_prod_32f (float* result, const float* a, const float* b, unsigned int n);
void volk_32f_accumulator_s32f(float* result, const float* a, unsigned int n);
void volk_32f_index_max_32u   (uint32_t* idx, const float* a, unsigned int n);

// ---- Conversions -------------------------------------------------------
void volk_8i_s32f_convert_32f (float*  out, const int8_t*  in, float scale, unsigned int n);
void volk_16i_s32f_convert_32f(float*  out, const int16_t* in, float scale, unsigned int n);
void volk_32i_s32f_convert_32f(float*  out, const int32_t* in, float scale, unsigned int n);
void volk_32f_s32f_convert_8i (int8_t*  out, const float* in, float scale, unsigned int n);
void volk_32f_s32f_convert_16i(int16_t* out, const float* in, float scale, unsigned int n);
void volk_32f_s32f_convert_32i(int32_t* out, const float* in, float scale, unsigned int n);

// ---- Complex arithmetic (interleaved 32fc) -----------------------------
void volk_32fc_x2_multiply_32fc       (lv_32fc_t* c, const lv_32fc_t* a, const lv_32fc_t* b, unsigned int n);
void volk_32fc_x2_dot_prod_32fc       (lv_32fc_t* r, const lv_32fc_t* a, const lv_32fc_t* b, unsigned int n);
void volk_32fc_32f_multiply_32fc      (lv_32fc_t* c, const lv_32fc_t* a, const float* b,     unsigned int n);
void volk_32fc_32f_dot_prod_32fc      (lv_32fc_t* r, const lv_32fc_t* a, const float* b,     unsigned int n);
void volk_32fc_conjugate_32fc         (lv_32fc_t* c, const lv_32fc_t* a,                     unsigned int n);
void volk_32fc_magnitude_32f          (float*     m, const lv_32fc_t* a,                     unsigned int n);
void volk_32fc_s32f_power_spectrum_32f(float*     p, const lv_32fc_t* a, float norm,         unsigned int n);
void volk_32fc_deinterleave_real_32f  (float*     r, const lv_32fc_t* a,                     unsigned int n);
void volk_32f_x2_interleave_32fc      (lv_32fc_t* c, const float* re,    const float* im,    unsigned int n);

// ---- Phase rotators (frequency translation) ----------------------------
// Both apply a per-sample multiply by a unit-magnitude phasor whose phase
// advances by `phaseDelta` per sample. The "_2" variant takes phaseDelta
// by pointer and is otherwise identical.
void volk_32fc_s32fc_x2_rotator_32fc (lv_32fc_t* out, const lv_32fc_t* in,
                                      const lv_32fc_t  phaseDelta,
                                      lv_32fc_t* phase, unsigned int n);
void volk_32fc_s32fc_x2_rotator2_32fc(lv_32fc_t* out, const lv_32fc_t* in,
                                      const lv_32fc_t* phaseDelta,
                                      lv_32fc_t* phase, unsigned int n);

#ifdef __cplusplus
}
#endif
